version: "3.8"

services:
  db:
    image: postgres:latest
    env_file:
      - ./.env.docker
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    env_file:
      - ./.env.docker

volumes:
  pgdata:
  rabbitmq_data:
